Display a comparison of the carbon footprint to a real life example
Theodo-UK/sustainability-calculator pull request #41
Opened 2023-07-18 16:27 UTC by Lerri-Cofannos

2023-07-18 16:36 UTC, juskek requested changes

2023-07-18 16:36 UTC, juskek commented on src/data/constants/RealLifeComparison.ts
> +const formatComparaison = (emission: number, comparison: string): string => {
just a typo

2023-07-18 16:36 UTC, juskek commented on src/data/constants/RealLifeComparison.ts
> +const formatComparaison = (emission: number, comparison: string): string => {
Can we also add some tests for this function?

2023-07-19 09:10 UTC, Lerri-Cofannos commented on src/utils/helpers/__tests__/getEmissionComparison.test.ts
> +            expect(getEmissionsComparison(0.2)).toBe("100% Google Search");
Good point! I have set the wrong comparison, it should be (emissions **>=** REAL_LIFE_EXAMPLES["Google Search"])

2023-07-19 09:50 UTC, juskek approved these changes

2023-07-19 09:50 UTC, merged